version: '3.1'


services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      
  adminer:
    image: adminer
    ports:
    - 8080:8080
  
  web:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ./code:/code
          - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
          - ./code:/code

